name: theatre_tickets_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  google_maps_flutter: ^2.9.0
  firebase_app_check: ^0.3.1+2
  firebase_core: ^3.5.0
  font_awesome_flutter: ^10.7.0
  google_sign_in: ^6.2.1
  loading_overlay: ^0.3.0
  http: ^1.2.2
  location: ^5.0.3
  geocoding: ^3.0.0
  connectivity_plus: ^6.0.5
  cached_network_image: ^3.4.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  firebase_auth: ^5.1.0
  stacked_firebase_auth: ^2.20.1
  sign_in_with_apple: ^6.1.2
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  razorpay_flutter: ^1.3.7
  dotted_border: ^2.1.0
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/movies/
    - assets/events/
    - assets/actors/
    - assets/plays/
    - assets/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700