name: global_translate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.1.0
  google_generative_ai: ^0.4.4
  flutter_tts: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - .env
